In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [3]:
x_train2 = x_train.reshape(len(x_train), 28 * 28)
df1 = pd.DataFrame(x_train2)


In [4]:
df1

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    0    0    0    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 784 columns]

In [5]:
df1_target = pd.DataFrame(y_train)

In [6]:
df1_target

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [7]:
df1['target'] = df1_target[0]
df1.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       5  
1    0       0  
2    0       4  
3    0       1  
4    0       9  

[5 rows x 785 columns]

# We did the merging for X_train and y_train, now lets do it for X_test and y_test

In [8]:
x_test2 = x_test.reshape(len(x_test), 28 * 28)
df2 = pd.DataFrame(x_test2)
df2_target = pd.DataFrame(y_test)
df2['target'] = df2_target[0]
df2.head()

##MERGING HAS BEEN DONE. WE NOW HAVE DF1 and DF2

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       7  
1    0       2  
2    0       1  
3    0       0  
4    0       4  

[5 rows x 785 columns]

In [9]:
##NOW GETTING THE DF IN WHICH WE WILL MERGE ALL OF THESE
df3 = pd.concat([df1, df2], ignore_index = True)
df3

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
1        0    0       0  
2        0    0       4  
3        0    0       1  
4        0    0       9  
...    ...  ...     ...  
69995    0    0       2  
69996    0    0       3  
69997    0    0       4  
69998    0    0       5  
69999    0    0       6  

[70000 rows x 785 columns]

In [10]:
# y = df3['target']
# y = pd.DataFrame(y)
# y.head()
df_train = df3.sample(frac=0.67,random_state=42)
df_test = df3.drop(df_train.index)
df_train

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
46730  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
48393  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
41416  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
34506  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
43725  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
12056  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
393    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
63024  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
11837  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
57774  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
46730    0    0       8  
48393    0    0       4  
41416    0    0       8  
34506    0    0       7  
43725    0    0       7  
...    ...  ...     ...  
12056    0    0       1  
393      0    0       8  
63024    0    0       4  
11837    0    0       3  
57774    0    0       7  

[46900 rows x 785 columns]

In [11]:
y_train = df_train['target']
y_train = pd.DataFrame(y_train)
y_train.head()
# df_train = df_train.drop('target', axis = 1, inplace = True)
# df_train.head()

target
46730       8
48393       4
41416       8
34506       7
43725       7

In [12]:
df_train = df_train.drop('target', axis=1)


In [13]:
df_train.head()
df_test

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
5      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
10     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
12     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
15     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69982  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69985  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69988  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69989  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
2        0    0       4  
5        0    0       2  
10       0    0       3  
12       0    0       3  
15       0    0       7  
...    ...  ...     ...  
69982    0    0       5  
69985    0    0       2  
69988    0    0       5  
69989    0    0       6  
69996    0    0       3  

[23100 rows x 785 columns]

In [14]:
y_test = df_test['target']
y_test = pd.DataFrame(y_test)
y_test.head()

target
2        4
5        2
10       3
12       3
15       7

In [15]:
df_test = df_test.drop('target', axis=1)


In [16]:
df_test.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
2     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
5     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
10    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
12    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
15    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    778  779  780  781  782  783  
2     0    0    0    0    0    0  
5     0    0    0    0    0    0  
10    0    0    0    0    0    0  
12    0    0    0    0    0    0  
15    0    0    0    0    0    0  

[5 rows x 784 columns]

# Converting these into NumPy arrays for use in the ANN model

In [17]:
x_train = df_train.to_numpy()
x_train
x_test = df_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# Performing the required pre-processing

In [18]:
x_train = x_train/255
x_test = x_test/255

In [19]:
#x_train[0]

In [20]:
X_trainf = x_train.reshape(len(x_train), 28 * 28)
#we choose to flatten the data in order to make the first input layer of the neural network have 784 values, since we currently have values stored in 28*28 form

In [21]:
X_testf = x_test.reshape(len(x_test), 28*28)

# MODEL 1 -- 150 neurons, 2 layers, sigmoid

In [22]:
model1 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model1.fit(X_trainf, y_train, epochs = 5)



Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.5660 - accuracy: 0.8589
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2115 - accuracy: 0.9384
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1561 - accuracy: 0.9543
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1240 - accuracy: 0.9630
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1002 - accuracy: 0.9700


In [23]:
model1.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 991us/step - loss: 0.1243 - accuracy: 0.9632


[0.12432883679866791, 0.963246762752533]

In [24]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 882us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2207,    1,    0,    1,    3,    8,   12,    2,    7,    3],
       [   1, 2586,   10,    3,    7,    2,    4,   12,   19,    3],
       [  18,    2, 2225,    6,   14,    1,    7,   15,   18,    1],
       [   7,    6,   26, 2216,    2,   65,    4,   20,   41,   14],
       [   1,    5,    9,    0, 2260,    2,   11,    4,    5,   40],
       [  14,    6,    3,   14,    5, 1982,   19,    1,   15,    7],
       [  11,    6,    1,    0,    7,   15, 2160,    0,    9,    0],
       [   5,    5,   16,    1,    9,    4,    0, 2277,    7,   10],
       [   8,   13,    7,   12,    3,   16,   12,    4, 2200,   10],
       [   7,    4,    0,   12,   45,   19,    1,   24,   20, 2138]])>

# MODEL 2 -- 100 Neurons, 3 Hidden Layers

In [25]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'sigmoid'),
    keras.layers.Dense(20, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model2.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 1.1122 - accuracy: 0.7091
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3158 - accuracy: 0.9219
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1987 - accuracy: 0.9463
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1546 - accuracy: 0.9569
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1263 - accuracy: 0.9647


In [26]:
model2.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1497 - accuracy: 0.9567


[0.14966340363025665, 0.9566666483879089]

In [27]:
y_predict = model2.predict(X_testf)

722/722 [==============================] - 1s 990us/step


In [28]:
y_predict[0]

array([1.32634938e-02, 5.08618598e-07, 1.49068877e-03, 3.57033656e-04,
       9.77852106e-01, 1.07054040e-03, 2.08174391e-03, 7.20832730e-04,
       1.03511215e-04, 3.05960770e-03], dtype=float32)

In [29]:
np.argmax(y_predict[0]) #gives the maximum value out of the given ones

4

In [30]:
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array

In [31]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices


In [32]:
cm #this is the confusion matrix, we are supposed to do this for all 15 of the models. Preferable if we beautify this a bit using matPlotLib, or seaborn if permitted by sir

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2206,    0,    0,    7,    4,    9,    9,    0,    5,    4],
       [   1, 2566,   11,    1,    5,   12,    4,   10,   29,    8],
       [  14,    7, 2164,   24,   20,    4,   21,   20,   33,    0],
       [   4,    3,   28, 2240,    0,   63,    3,   19,   27,   14],
       [   5,    2,    8,    0, 2231,    4,   10,    3,    8,   66],
       [  16,    3,    4,   23,    6, 1960,   17,    0,   23,   14],
       [  15,    4,    4,    0,    8,   21, 2143,    0,   14,    0],
       [   1,    5,   17,   13,   20,    2,    0, 2225,    9,   42],
       [   6,   15,    5,   14,    5,   15,   18,    2, 2185,   20],
       [  10,    0,    0,    7,   28,   17,    0,   16,   13, 2179]])>

# MODEL 3 -- 150 Neurons, 2 Hidden Layers, ReLU

In [33]:
model3 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2960 - accuracy: 0.9142
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1305 - accuracy: 0.9611
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0909 - accuracy: 0.9723
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0703 - accuracy: 0.9781
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0560 - accuracy: 0.9818


In [34]:
model3.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1043 - accuracy: 0.9698


[0.1042722687125206, 0.9697835445404053]

In [35]:
y_predict = model3.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2205,    3,    5,    0,    2,    8,   12,    1,    7,    1],
       [   1, 2620,    3,    2,    4,    0,    0,   14,    2,    1],
       [   8,   14, 2234,    4,    6,    2,    5,   15,   19,    0],
       [   2,    7,   23, 2293,    0,   24,    2,   19,   28,    3],
       [   3,    7,   13,    0, 2276,    0,   17,    9,    3,    9],
       [   6,    4,    2,   12,    3, 1999,   19,    1,   14,    6],
       [   9,    9,    0,    1,    1,    4, 2177,    0,    8,    0],
       [   0,    7,   12,    1,    7,    3,    2, 2285,    4,   13],
       [   4,   22,   14,   10,    3,   13,    8,    6, 2199,    6],
       [   2,    1,    4,    9,   70,   13,    3,   26,   28, 2114]])>

In [36]:
model4 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 1ms/step - loss: 0.3091 - accuracy: 0.9098
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1437 - accuracy: 0.9567
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0994 - accuracy: 0.9693
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0726 - accuracy: 0.9776
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0570 - accuracy: 0.9826


In [37]:
model4.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.0955 - accuracy: 0.9718


[0.09554368257522583, 0.9717748761177063]

In [38]:
y_predict = model4.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2221,    1,    0,    3,    2,    8,    1,    2,    5,    1],
       [   1, 2605,    9,    3,    3,    0,    4,    8,   11,    3],
       [  14,    1, 2241,    7,   16,    2,    3,   14,    9,    0],
       [   3,    9,   18, 2302,    2,   25,    1,   10,   22,    9],
       [   3,    4,    8,    0, 2270,    0,    8,    4,    7,   33],
       [  16,    4,    2,   13,    3, 1987,   13,    0,   17,   11],
       [  16,    5,    2,    0,    6,   13, 2155,    2,   10,    0],
       [   2,    7,   17,    5,    8,    1,    2, 2262,    8,   22],
       [  13,   10,    5,   10,    2,    8,   10,    1, 2220,    6],
       [   3,    4,    2,   10,   31,    9,    2,   12,   12, 2185]])>

In [39]:
model5 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model5.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3586 - accuracy: 0.8950
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1627 - accuracy: 0.9519
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1212 - accuracy: 0.9628
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0996 - accuracy: 0.9694
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0827 - accuracy: 0.9743


In [40]:
model5.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1400 - accuracy: 0.9600


[0.1400110125541687, 0.9599999785423279]

In [41]:
y_predict = model5.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2203,    1,    7,    5,    3,    2,   15,    1,    5,    2],
       [   0, 2610,    6,    1,   10,    0,    1,    5,    4,   10],
       [  13,    7, 2238,   10,   16,    0,    6,    8,    7,    2],
       [   3,    9,   32, 2290,    2,   11,    5,   13,   21,   15],
       [   1,    8,    5,    0, 2294,    0,    7,    2,    2,   18],
       [  11,    9,    3,   51,   16, 1890,   26,    3,   22,   35],
       [  11,    7,    4,    1,   16,    4, 2163,    0,    3,    0],
       [   5,    8,   21,    7,   26,    0,    2, 2228,    2,   35],
       [   9,   30,   31,   20,   22,    5,    9,    8, 2089,   62],
       [   6,    4,    1,   10,   60,    2,    1,   11,    4, 2171]])>

In [42]:
model6 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'tanh'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model6.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model6.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3908 - accuracy: 0.8995
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1620 - accuracy: 0.9528
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1171 - accuracy: 0.9654
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0956 - accuracy: 0.9713
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0764 - accuracy: 0.9772


In [43]:
model6.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1238 - accuracy: 0.9646


[0.1238015741109848, 0.9646320343017578]

In [44]:
y_predict = model6.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2206,    0,    1,    4,    4,    5,    7,    0,   13,    4],
       [   1, 2579,   10,   11,    4,    4,    5,    7,   20,    6],
       [  10,    3, 2226,   19,   19,    2,    4,    6,   15,    3],
       [   1,    2,    9, 2326,    1,   19,    0,    8,   31,    4],
       [   5,    4,    8,    3, 2263,    2,    5,    3,    7,   37],
       [  10,    0,    3,   31,    3, 1971,   12,    1,   25,   10],
       [  10,    4,    2,    0,   14,   29, 2136,    0,   14,    0],
       [   7,    8,   18,   12,   16,    4,    0, 2206,    9,   54],
       [   3,    8,    9,   19,    3,   10,    5,    0, 2217,   11],
       [   3,    4,    2,   29,   35,   15,    1,   11,   17, 2153]])>

In [45]:
model7 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model7.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model7.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4867 - accuracy: 0.8677
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1936 - accuracy: 0.9436
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1410 - accuracy: 0.9585
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1129 - accuracy: 0.9662
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0943 - accuracy: 0.9713


In [46]:
model7.evaluate(X_testf, y_test)

722/722 [==============================] - 2s 2ms/step - loss: 0.1193 - accuracy: 0.9649


[0.1192518100142479, 0.9649350643157959]

In [47]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2207,    1,    0,    1,    3,    8,   12,    2,    7,    3],
       [   1, 2586,   10,    3,    7,    2,    4,   12,   19,    3],
       [  18,    2, 2225,    6,   14,    1,    7,   15,   18,    1],
       [   7,    6,   26, 2216,    2,   65,    4,   20,   41,   14],
       [   1,    5,    9,    0, 2260,    2,   11,    4,    5,   40],
       [  14,    6,    3,   14,    5, 1982,   19,    1,   15,    7],
       [  11,    6,    1,    0,    7,   15, 2160,    0,    9,    0],
       [   5,    5,   16,    1,    9,    4,    0, 2277,    7,   10],
       [   8,   13,    7,   12,    3,   16,   12,    4, 2200,   10],
       [   7,    4,    0,   12,   45,   19,    1,   24,   20, 2138]])>

In [48]:
model8 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model8.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model8.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4098 - accuracy: 0.8874
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1902 - accuracy: 0.9436
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1375 - accuracy: 0.9587
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1069 - accuracy: 0.9678
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0859 - accuracy: 0.9742


In [49]:
model8.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1260 - accuracy: 0.9613


[0.12595756351947784, 0.9613419771194458]

In [50]:
y_predict = model8.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2216,    1,    0,    2,    1,    7,    6,    4,    3,    4],
       [   1, 2613,    3,    4,    3,    2,    3,   10,    1,    7],
       [  16,   18, 2210,   14,    7,    1,    8,   19,   13,    1],
       [   5,    7,   13, 2271,    0,   68,    4,   15,   10,    8],
       [   6,    5,    9,    0, 2230,    2,   17,    8,    5,   55],
       [  13,    5,    1,   17,    2, 2002,   16,    0,    4,    6],
       [  17,    7,    1,    0,    3,   16, 2164,    0,    1,    0],
       [   4,    7,   14,    3,    4,    3,    1, 2281,    3,   14],
       [  16,   28,    9,   38,    6,   61,   23,    9, 2044,   51],
       [   6,    4,    1,   10,   25,   18,    2,   27,    1, 2176]])>

In [51]:
model9 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model9.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model9.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3978 - accuracy: 0.8887
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1868 - accuracy: 0.9437
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1323 - accuracy: 0.9602
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1003 - accuracy: 0.9694
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0802 - accuracy: 0.9757


In [52]:
model9.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1136 - accuracy: 0.9654


[0.11355066299438477, 0.9654112458229065]

In [53]:
y_predict = model9.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2196,    1,    1,    7,    3,    4,   17,    4,   10,    1],
       [   1, 2613,    6,    6,    9,    0,    4,    4,    3,    1],
       [   9,   11, 2221,   17,   10,    0,    7,   17,   14,    1],
       [   2,    8,   12, 2328,    1,   11,    1,   15,   21,    2],
       [   1,    5,    5,    0, 2295,    1,   15,    5,    5,    5],
       [   8,   10,    2,   46,    6, 1934,   19,    1,   31,    9],
       [   7,    5,    0,    1,    6,    5, 2176,    0,    9,    0],
       [   1,    9,    9,    8,   11,    0,    1, 2278,    6,   11],
       [   6,   17,    8,   18,    5,    5,    5,    1, 2215,    5],
       [   6,    9,    0,   19,  124,   12,    2,   28,   25, 2045]])>

In [54]:
model10 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model10.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model10.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2755 - accuracy: 0.9201
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1159 - accuracy: 0.9654
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0817 - accuracy: 0.9739
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0604 - accuracy: 0.9810
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0487 - accuracy: 0.9845


In [55]:
model10.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.0988 - accuracy: 0.9717


[0.09875952452421188, 0.9717316031455994]

In [56]:
y_predict = model10.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2209,    3,    5,    3,    0,    6,    8,    3,    6,    1],
       [   0, 2614,    4,    3,   10,    1,    0,    8,    2,    5],
       [   8,    3, 2245,   18,    9,    1,    0,   13,   10,    0],
       [   1,    4,   10, 2344,    0,   14,    0,   10,    9,    9],
       [   1,    4,    8,    0, 2270,    1,    7,    6,    1,   39],
       [   7,    5,    3,   23,    4, 1983,    8,    1,   14,   18],
       [  14,   12,    0,    1,    4,    8, 2159,    0,   11,    0],
       [   5,    8,    9,    4,    3,    4,    2, 2260,    2,   37],
       [   7,   20,    9,   33,    5,    6,    4,    6, 2173,   22],
       [   6,    3,    1,   11,   27,   10,    2,   16,    4, 2190]])>

In [57]:
model11 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'sigmoid'),
    keras.layers.Dense(40, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model11.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model11.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.8055 - accuracy: 0.7990
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2585 - accuracy: 0.9298
Epoch 3/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.1813 - accuracy: 0.9494
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1393 - accuracy: 0.9606
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1136 - accuracy: 0.9680


In [58]:
model11.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1433 - accuracy: 0.9583


[0.14327916502952576, 0.958268404006958]

In [59]:
y_predict = model11.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2194,    0,    8,    6,    5,    6,   17,    0,    8,    0],
       [   1, 2572,   17,    8,    7,    5,    6,    8,   19,    4],
       [  15,    3, 2229,   17,   10,    1,   10,    5,   17,    0],
       [   2,    3,   35, 2253,    1,   46,    2,   13,   41,    5],
       [   3,    5,    4,    0, 2263,    1,   21,    3,   13,   24],
       [   9,    5,    2,   15,    5, 1973,   19,    0,   31,    7],
       [  11,    2,    1,    0,    7,   15, 2165,    0,    8,    0],
       [   8,    8,   43,   14,   13,    4,    2, 2226,    3,   13],
       [   6,   14,   12,   12,    2,   27,   17,    1, 2187,    7],
       [  10,    5,    2,   17,   81,   18,    2,   20,   41, 2074]])>

In [60]:
model12 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model12.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model12.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 5s 3ms/step - loss: 0.3301 - accuracy: 0.9018
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1432 - accuracy: 0.9568
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1035 - accuracy: 0.9686
Epoch 4/5
1466/1466 [==============================] - 6s 4ms/step - loss: 0.0838 - accuracy: 0.9734
Epoch 5/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.0719 - accuracy: 0.9770


In [61]:
model12.evaluate(X_testf, y_test)

722/722 [==============================] - 2s 2ms/step - loss: 0.1032 - accuracy: 0.9695


[0.10321241617202759, 0.9695237874984741]

In [62]:
y_predict = model12.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 2s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2221,    0,    1,    0,    0,    0,    6,    2,   13,    1],
       [   0, 2581,   10,    4,    2,    0,    2,   25,   21,    2],
       [  23,    4, 2219,    8,    9,    1,    7,   17,   19,    0],
       [   3,    3,   20, 2302,    1,   26,    1,   17,   22,    6],
       [   3,    0,    4,    0, 2294,    0,    9,    5,    4,   18],
       [  14,    2,    1,   26,    7, 1970,   15,    3,   22,    6],
       [  21,    5,    2,    1,    4,    8, 2158,    0,   10,    0],
       [   3,    3,    8,    2,   12,    0,    1, 2284,    5,   16],
       [   7,    6,    9,    6,    4,    9,   12,    4, 2215,   13],
       [   2,    5,    0,   15,   52,   13,    1,   20,   10, 2152]])>

In [63]:
model13 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'tanh'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model13.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model13.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.3219 - accuracy: 0.9104
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1440 - accuracy: 0.9577
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1039 - accuracy: 0.9687
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0784 - accuracy: 0.9760
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0638 - accuracy: 0.9805


In [64]:
model13.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1072 - accuracy: 0.9672


[0.10724849253892899, 0.9671861529350281]

In [65]:
y_predict = model13.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2193,    0,    4,    6,    4,    5,   12,    2,   15,    3],
       [   0, 2599,    9,    5,    8,    0,    1,   12,   11,    2],
       [  11,    3, 2234,   14,    8,    4,    6,    8,   19,    0],
       [   0,    3,   12, 2306,    0,   18,    1,   12,   48,    1],
       [   2,    5,    5,    1, 2284,    1,   14,    2,    4,   19],
       [   7,    3,    2,   38,    9, 1961,   10,    3,   25,    8],
       [   8,    4,    2,    1,    8,   12, 2163,    0,   11,    0],
       [   3,    8,   16,    6,   16,    2,    0, 2268,    9,    6],
       [   7,   15,    7,   13,    4,   17,    7,    4, 2204,    7],
       [   3,    2,    2,   14,   50,   17,    1,   24,   27, 2130]])>

In [66]:
model14 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model14.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model14.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4099 - accuracy: 0.8836
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1780 - accuracy: 0.9460
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1291 - accuracy: 0.9616
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1041 - accuracy: 0.9680
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0846 - accuracy: 0.9738


In [67]:
model14.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1333 - accuracy: 0.9582


[0.13331972062587738, 0.9582251310348511]

In [68]:
y_predict = model14.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2194,    0,    3,    1,    2,    4,    5,    3,   24,    8],
       [   0, 2593,   13,    2,    1,    2,    2,    2,   21,   11],
       [   9,    4, 2234,    6,    9,    1,    5,   10,   29,    0],
       [   1,   13,   31, 2208,    1,   32,    0,   18,   76,   21],
       [   3,   10,   13,    0, 2171,    1,   12,    5,   21,  101],
       [   7,    5,    4,   14,    4, 1952,   15,    0,   45,   20],
       [  16,    9,    5,    0,    4,    7, 2145,    0,   23,    0],
       [   1,    8,   24,    3,    5,    1,    0, 2206,   25,   61],
       [   4,   10,    9,    3,    0,    5,    3,    0, 2243,    8],
       [   3,    6,    3,    6,   15,    7,    1,    8,   32, 2189]])>

In [69]:
model15 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model15.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model15.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4685 - accuracy: 0.8738
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2069 - accuracy: 0.9399
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1569 - accuracy: 0.9537
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1252 - accuracy: 0.9629
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1063 - accuracy: 0.9676


In [70]:
model15.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1339 - accuracy: 0.9598


[0.13388650119304657, 0.9598268270492554]

In [71]:
y_predict = model15.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2197,    0,    3,    6,    6,   10,   10,    3,    7,    2],
       [   1, 2602,    7,    4,    7,    4,    1,   10,    9,    2],
       [  19,    9, 2193,   11,   21,    6,    6,   25,   16,    1],
       [   0,    8,   18, 2291,    1,   38,    1,   24,   16,    4],
       [   1,    4,    8,    1, 2290,    1,    6,    4,    6,   16],
       [   8,   11,    1,   26,    4, 1984,   12,    1,   14,    5],
       [  19,    9,    3,    0,   29,   28, 2109,    1,   11,    0],
       [   4,    8,   12,    2,   12,    2,    0, 2278,    5,   11],
       [   7,   23,   13,   24,    8,   24,    3,    7, 2167,    9],
       [   4,    5,    0,   30,   87,   23,    0,   41,   19, 2061]])>